// packages/nextjs/src/ui/IssueReporterButton.tsx
'use client';

import React from 'react';
import { Bug } from 'lucide-react';
import { useBlario } from '../hooks/useBlario';
import { useBlarioContext } from '../provider/BlarioProvider';
import { Button } from './components/button';
import { cn } from './lib/utils';

// Types
export type ButtonVariant = 'default' | 'destructive' | 'outline' | 'secondary' | 'ghost' | 'link';
export type ButtonSize = 'default' | 'sm' | 'lg' | 'icon';
export type ButtonPosition = 'bottom-right' | 'bottom-left' | 'top-right' | 'top-left';
export type ButtonDisplayVariant = 'floating' | 'inline';

export interface IssueReporterButtonProps {
  // Display options
  variant?: ButtonDisplayVariant;
  position?: ButtonPosition;
  unstyled?: boolean;

  // Styling
  className?: string;
  buttonVariant?: ButtonVariant;
  buttonSize?: ButtonSize;

  // Content customization
  children?: React.ReactNode;
  icon?: React.ReactNode;
  iconClassName?: string;
  textClassName?: string;
  hideIcon?: boolean;
  hideText?: boolean;

  // Behavior
  category?: string;
  prefill?: Record<string, any>;
  'aria-label'?: string;
}

// Constants
const POSITION_CLASSES: Record<ButtonPosition, string> = {
  'bottom-right': 'bottom-4 right-4',
  'bottom-left': 'bottom-4 left-4',
  'top-right': 'top-4 right-4',
  'top-left': 'top-4 left-4',
};

const DEFAULT_FLOATING_CLASSES = 'fixed z-50 h-14 w-14 rounded-full shadow-lg hover:shadow-xl transition-all';
const DEFAULT_ICON_SIZE = 'h-6 w-6';
const DEFAULT_ARIA_LABEL = 'Report an issue';
const DEFAULT_TEXT = 'Report Issue';

// Subcomponents
interface ButtonContentProps {
  icon?: React.ReactNode;
  hideIcon?: boolean;
  hideText?: boolean;
  iconClassName?: string;
  textClassName?: string;
  children?: React.ReactNode;
  isStyled?: boolean;
  isInline?: boolean;
}

const ButtonContent: React.FC<ButtonContentProps> = ({
  icon,
  hideIcon,
  hideText,
  iconClassName,
  textClassName,
  children,
  isStyled = false,
  isInline = false,
}) => {
  const iconElement = !hideIcon && (
    icon || (
      <Bug
        className={
          isStyled && isInline
            ? cn('blario-button-icon-inline', iconClassName)
            : iconClassName || DEFAULT_ICON_SIZE
        }
      />
    )
  );

  const textElement = !hideText && (
    children || DEFAULT_TEXT
  );

  if (!textElement) {
    return <>{iconElement}</>;
  }

  const textWrapper = isStyled && isInline ? (
    <span className={cn('blario-button-text', textClassName)}>
      {textElement}
    </span>
  ) : (
    <span className={textClassName}>{textElement}</span>
  );

  return (
    <>
      {iconElement}
      {textWrapper}
    </>
  );
};

// Main component
export function IssueReporterButton({
  // Display options
  variant = 'floating',
  position,
  unstyled = false,

  // Styling
  className,
  buttonVariant,
  buttonSize,

  // Content customization
  children,
  icon,
  iconClassName,
  textClassName,
  hideIcon = false,
  hideText = false,

  // Behavior
  category,
  prefill,
  'aria-label': ariaLabel = DEFAULT_ARIA_LABEL,
}: IssueReporterButtonProps) {
  const { openReporter } = useBlario();
  const { config } = useBlarioContext();

  const finalPosition = position ?? config.theme?.position ?? 'bottom-right';

  const handleClick = React.useCallback(() => {
    openReporter({ category, prefill });
  }, [openReporter, category, prefill]);

  const contentProps: ButtonContentProps = {
    icon,
    hideIcon,
    hideText,
    iconClassName,
    textClassName,
    children,
    isStyled: !unstyled,
    isInline: variant === 'inline',
  };

  // Unstyled button (complete control)
  if (unstyled) {
    const baseClasses = variant === 'floating'
      ? cn('fixed z-50', POSITION_CLASSES[finalPosition])
      : undefined;

    return (
      <button
        onClick={handleClick}
        className={cn(baseClasses, className)}
        aria-label={ariaLabel}
        data-tour-id="issue-reporter-button"
      >
        <ButtonContent {...contentProps} />
      </button>
    );
  }

  // Inline styled button
  if (variant === 'inline') {
    return (
      <Button
        onClick={handleClick}
        className={cn('blario-button-inline', className)}
        aria-label={ariaLabel}
        variant={buttonVariant}
        size={buttonSize}
        data-tour-id="issue-reporter-button"
      >
        <ButtonContent {...contentProps} />
      </Button>
    );
  }

  // Floating styled button - icon only by default
  return (
    <Button
      onClick={handleClick}
      className={cn(
        DEFAULT_FLOATING_CLASSES,
        POSITION_CLASSES[finalPosition],
        config.theme?.accent && `bg-[${config.theme.accent}]`,
        className
      )}
      size={buttonSize || 'icon'}
      variant={buttonVariant}
      aria-label={ariaLabel}
      data-tour-id="issue-reporter-button"
    >
      <ButtonContent {...contentProps} hideText={hideText === undefined ? true : hideText} />
    </Button>
  );
}

// packages/vue/src/components/IssueReporterButton.vue
<template>
  <button
    v-if="unstyled"
    :class="unstyledClasses"
    :aria-label="ariaLabel"
    data-tour-id="issue-reporter-button"
    @click="handleClick"
  >
    <slot>
      <Bug v-if="!hideIcon" :class="iconClass" />
      <span v-if="!hideText" :class="textClassName">{{ children || DEFAULT_TEXT }}</span>
    </slot>
  </button>

  <button
    v-else-if="variant === 'inline'"
    :class="inlineClasses"
    :aria-label="ariaLabel"
    data-tour-id="issue-reporter-button"
    @click="handleClick"
  >
    <slot>
      <Bug v-if="!hideIcon" :class="iconClass" />
      <span v-if="!hideText" :class="textClassName">{{ children || DEFAULT_TEXT }}</span>
    </slot>
  </button>

  <button
    v-else
    :class="floatingClasses"
    :aria-label="ariaLabel"
    data-tour-id="issue-reporter-button"
    @click="handleClick"
  >
    <slot>
      <Bug v-if="!hideIcon" :class="iconClass" />
      <span v-if="!hideText && !defaultHideText" :class="textClassName">{{ children || DEFAULT_TEXT }}</span>
    </slot>
  </button>
</template>

<script setup lang="ts">
import { computed, inject } from 'vue';
import { Bug } from 'lucide-vue-next';
import { useBlario } from '../composables/useBlario';
import { BlarioKey } from '../plugin/BlarioPlugin';
import { cn } from '../lib/cn';

// Types
export type ButtonVariant = 'default' | 'destructive' | 'outline' | 'secondary' | 'ghost' | 'link';
export type ButtonSize = 'default' | 'sm' | 'lg' | 'icon';
export type ButtonPosition = 'bottom-right' | 'bottom-left' | 'top-right' | 'top-left';
export type ButtonDisplayVariant = 'floating' | 'inline';

export interface IssueReporterButtonProps {
  variant?: ButtonDisplayVariant;
  position?: ButtonPosition;
  unstyled?: boolean;
  className?: string;
  buttonVariant?: ButtonVariant;
  buttonSize?: ButtonSize;
  children?: string;
  icon?: any;
  iconClassName?: string;
  textClassName?: string;
  hideIcon?: boolean;
  hideText?: boolean;
  category?: string;
  prefill?: Record<string, any>;
  ariaLabel?: string;
}

const props = withDefaults(defineProps<IssueReporterButtonProps>(), {
  variant: 'floating',
  unstyled: false,
  hideIcon: false,
  hideText: false,
  ariaLabel: 'Report an issue',
});

// Constants
const POSITION_CLASSES: Record<ButtonPosition, string> = {
  'bottom-right': 'bottom-4 right-4',
  'bottom-left': 'bottom-4 left-4',
  'top-right': 'top-4 right-4',
  'top-left': 'top-4 left-4',
};

const DEFAULT_FLOATING_CLASSES = 'fixed z-50 h-14 w-14 rounded-full shadow-lg hover:shadow-xl transition-all';
const DEFAULT_ICON_SIZE = 'h-6 w-6';
const DEFAULT_TEXT = 'Report Issue';

const { openReporter } = useBlario();
const blario = inject(BlarioKey);

const finalPosition = computed(() =>
  props.position ?? blario?.state.config.theme?.position ?? 'bottom-right'
);

const defaultHideText = computed(() =>
  props.variant === 'floating' && props.hideText === undefined
);

const iconClass = computed(() =>
  props.iconClassName || DEFAULT_ICON_SIZE
);

const unstyledClasses = computed(() =>
  cn(
    props.variant === 'floating' ? `fixed z-50 ${POSITION_CLASSES[finalPosition.value]}` : undefined,
    props.className
  )
);

const inlineClasses = computed(() =>
  cn('blario-button-inline', props.className)
);

const floatingClasses = computed(() =>
  cn(
    DEFAULT_FLOATING_CLASSES,
    POSITION_CLASSES[finalPosition.value],
    blario?.state.config.theme?.accent && `bg-[${blario.state.config.theme.accent}]`,
    props.className
  )
);

const handleClick = () => {
  openReporter({
    category: props.category,
    prefill: props.prefill
  });
};
</script>
