// packages/vue/src/components/BlarioProvider.vue
<template>
  <div class="blario-provider">
    <slot />
    <IssueReporterModal />
  </div>
</template>

<script setup lang="ts">
import { provide, reactive, readonly, watch, onUnmounted } from 'vue';
import type { DiagnosticResponse, User } from '@blario/core';
import {
  getCaptureManager,
  resetCaptureManager,
  getStorageManager,
  resetStorageManager,
  getApiClient,
  resetApiClient,
} from '@blario/core';
import IssueReporterModal from './IssueReporterModal.vue';
import type { BlarioState, BlarioActions, BlarioContext } from '../plugin/BlarioPlugin';
import { BlarioKey } from '../plugin/BlarioPlugin';

export interface BlarioProviderProps {
  publishableKey: string;
  apiBaseUrl?: string;
  user?: User;
  locale?: 'en' | 'es';
  capture?: {
    console?: boolean;
    networkSample?: boolean;
    maxConsoleLogs?: number;
    maxNetworkLogs?: number;
  };
  theme?: {
    mode?: 'light' | 'dark';
    position?: 'bottom-right' | 'bottom-left' | 'top-right' | 'top-left';
    accent?: string;
    className?: string;
  };
  redaction?: {
    patterns?: RegExp[];
    customRedactor?: (text: string) => string;
  };
  rateLimit?: {
    maxRequests?: number;
    windowMs?: number;
  };
}

const props = withDefaults(defineProps<BlarioProviderProps>(), {
  apiBaseUrl: 'https://api.blar.io',
  locale: 'en',
  capture: () => ({}),
  theme: () => ({}),
  redaction: () => ({}),
  rateLimit: () => ({}),
});

const emit = defineEmits<{
  afterSubmit: [issueId: string];
  error: [error: Error];
}>();

// Initialize managers
const captureManager = getCaptureManager(
  {
    maxConsoleLogs: props.capture?.maxConsoleLogs ?? 50,
    maxNetworkLogs: props.capture?.maxNetworkLogs ?? 20,
    captureConsole: props.capture?.console ?? true,
    captureNetwork: props.capture?.networkSample ?? false,
  },
  {
    getAppVersion: () => import.meta.env.VITE_APP_VERSION,
    getRelease: () => import.meta.env.VITE_RELEASE,
  }
);

const storageManager = getStorageManager();
const apiClient = getApiClient({
  apiBaseUrl: props.apiBaseUrl,
  publishableKey: props.publishableKey,
});

const rateLimitState = {
  requests: [] as number[],
  maxRequests: props.rateLimit?.maxRequests ?? 10,
  windowMs: props.rateLimit?.windowMs ?? 60000,
};

// Reactive state
const state = reactive<BlarioState>({
  config: {
    publishableKey: props.publishableKey,
    apiBaseUrl: props.apiBaseUrl,
    user: props.user,
    locale: props.locale,
    capture: {
      console: props.capture?.console ?? true,
      networkSample: props.capture?.networkSample ?? false,
      maxConsoleLogs: props.capture?.maxConsoleLogs ?? 50,
      maxNetworkLogs: props.capture?.maxNetworkLogs ?? 20,
    },
    theme: {
      mode: props.theme?.mode ?? 'light',
      position: props.theme?.position ?? 'bottom-right',
      accent: props.theme?.accent,
      className: props.theme?.className,
    },
    redaction: props.redaction,
    rateLimit: {
      maxRequests: props.rateLimit?.maxRequests ?? 10,
      windowMs: props.rateLimit?.windowMs ?? 60000,
    },
    onAfterSubmit: (issueId: string) => emit('afterSubmit', issueId),
    onError: (error: Error) => emit('error', error),
  },
  isModalOpen: false,
  reporterOptions: {},
  lastDiagnostic: null,
  isSubmitting: false,
  user: props.user,
  locale: props.locale,
});

// Start capture
captureManager.startCapture();

// Load latest diagnostic from storage
const latestDiagnostic = storageManager.getLatestDiagnostic();
if (latestDiagnostic && !latestDiagnostic.viewed) {
  state.lastDiagnostic = latestDiagnostic;
}

// Watch for theme changes
watch(() => props.theme?.mode, (mode) => {
  if (typeof window !== 'undefined') {
    const root = document.documentElement;
    if (mode === 'dark') {
      root.classList.add('dark');
    } else {
      root.classList.remove('dark');
    }
  }
}, { immediate: true });

const checkRateLimit = (): boolean => {
  const now = Date.now();
  const { requests, maxRequests, windowMs } = rateLimitState;

  const validRequests = requests.filter(time => now - time < windowMs);
  rateLimitState.requests = validRequests;

  if (validRequests.length >= maxRequests) {
    return false;
  }

  rateLimitState.requests.push(now);
  return true;
};

// Actions
const actions: BlarioActions = {
  openReporter(opts = {}) {
    state.reporterOptions = opts;
    state.isModalOpen = true;
  },

  closeReporter() {
    state.isModalOpen = false;
    state.reporterOptions = {};
  },

  async submitIssue(formData: any): Promise<DiagnosticResponse | null> {
    if (!checkRateLimit()) {
      const error = new Error('Rate limit exceeded. Please try again later.');
      emit('error', error);
      throw error;
    }

    state.isSubmitting = true;

    try {
      const { attachments, ...formFields } = formData;

      const payload = {
        publishableKey: props.publishableKey,
        user: props.user,
        meta: captureManager.getCaptureMeta(),
        console: props.capture?.console !== false ? captureManager.getConsoleLogs() : undefined,
        network: props.capture?.networkSample ? captureManager.getNetworkLogs() : undefined,
        form: formFields,
      };

      const { issueId } = await apiClient.submitIssue(payload);

      emit('afterSubmit', issueId);

      return { issueId, status: 'pending' as const, diagnostic: undefined };
    } catch (error) {
      const err = error instanceof Error ? error : new Error('Failed to submit issue');
      emit('error', err);
      throw err;
    } finally {
      state.isSubmitting = false;
    }
  },

  clearDiagnostic() {
    if (state.lastDiagnostic?.issueId) {
      storageManager.markDiagnosticAsViewed(state.lastDiagnostic.issueId);
    }
    state.lastDiagnostic = null;
  },
};

// Provide context
const context: BlarioContext = {
  state: readonly(state) as Readonly<BlarioState>,
  actions,
};

provide(BlarioKey, context);

// Cleanup on unmount
onUnmounted(() => {
  captureManager.stopCapture();
  resetCaptureManager();
  resetStorageManager();
  resetApiClient();
});
</script>

// packages/nextjs/src/provider/BlarioProvider.tsx
'use client';

import {
  createContext,
  useContext,
  useEffect,
  useMemo,
  useRef,
  useState,
  ReactNode,
} from 'react';
import { usePathname, useSearchParams } from 'next/navigation';
import type { BlarioConfig, DiagnosticResponse, User } from '@blario/core';
import {
  getCaptureManager,
  resetCaptureManager,
  getStorageManager,
  resetStorageManager,
  getApiClient,
  resetApiClient,
} from '@blario/core';
import { IssueReporterModal } from '../ui/IssueReporterModal';
import { cn } from '../lib/cn';
import '../styles/theme.css';

export interface BlarioContextValue {
  config: BlarioConfig;
  isModalOpen: boolean;
  openReporter: (options?: { category?: string; prefill?: Record<string, any> }) => void;
  closeReporter: () => void;
  reporterOptions?: { category?: string; prefill?: Record<string, any> };
  lastDiagnostic: DiagnosticResponse | null;
  isSubmitting: boolean;
  submitIssue: (formData: any) => Promise<DiagnosticResponse | null>;
  clearDiagnostic: () => void;
  user?: User;
  locale: 'en' | 'es';
}

const BlarioContext = createContext<BlarioContextValue | null>(null);

export interface BlarioProviderProps {
  publishableKey: string;
  apiBaseUrl?: string;
  user?: User;
  locale?: 'en' | 'es';
  capture?: {
    console?: boolean;
    networkSample?: boolean;
    maxConsoleLogs?: number;
    maxNetworkLogs?: number;
  };
  theme?: {
    mode?: 'light' | 'dark';
    position?: 'bottom-right' | 'bottom-left' | 'top-right' | 'top-left';
    accent?: string;
    className?: string;
  };
  redaction?: {
    patterns?: RegExp[];
    customRedactor?: (text: string) => string;
  };
  rateLimit?: {
    maxRequests?: number;
    windowMs?: number;
  };
  onAfterSubmit?: (issueId: string) => void;
  onError?: (error: Error) => void;
  children: ReactNode;
}

export function BlarioProvider({
  publishableKey,
  apiBaseUrl = 'https://api.blar.io',
  user,
  locale = 'en',
  capture = {},
  theme = {},
  redaction = {},
  rateLimit = {},
  onAfterSubmit,
  onError,
  children,
}: BlarioProviderProps) {
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [reporterOptions, setReporterOptions] = useState<{
    category?: string;
    prefill?: Record<string, any>;
  }>({});
  const [lastDiagnostic, setLastDiagnostic] = useState<DiagnosticResponse | null>(null);
  const [isSubmitting, setIsSubmitting] = useState(false);

  const pathname = usePathname();
  const searchParams = useSearchParams();

  const captureManagerRef = useRef(getCaptureManager({
    maxConsoleLogs: capture.maxConsoleLogs ?? 50,
    maxNetworkLogs: capture.maxNetworkLogs ?? 20,
    captureConsole: capture.console ?? true,
    captureNetwork: capture.networkSample ?? false,
  }));

  const storageManagerRef = useRef(getStorageManager());
  const apiClientRef = useRef(getApiClient({
    apiBaseUrl,
    publishableKey,
  }));

  const rateLimitRef = useRef({
    requests: [] as number[],
    maxRequests: rateLimit.maxRequests ?? 10,
    windowMs: rateLimit.windowMs ?? 60000,
  });

  useEffect(() => {
    const captureManager = captureManagerRef.current;
    captureManager.startCapture();

    if (typeof window !== 'undefined') {
      const currentUrl = `${pathname}${searchParams.toString() ? `?${searchParams.toString()}` : ''}`;
      captureManager.trackRoute(currentUrl);
    }

    return () => {
      captureManager.stopCapture();
    };
  }, [pathname, searchParams]);

  // Apply dark mode class to document root for better compatibility
  useEffect(() => {
    if (typeof window !== 'undefined') {
      const root = document.documentElement;
      if (theme.mode === 'dark') {
        root.classList.add('dark');
      } else {
        root.classList.remove('dark');
      }
    }
  }, [theme.mode]);

  useEffect(() => {
    const storageManager = storageManagerRef.current;
    const latestDiagnostic = storageManager.getLatestDiagnostic();

    if (latestDiagnostic && !latestDiagnostic.viewed) {
      setLastDiagnostic(latestDiagnostic);
    }
  }, []);

  useEffect(() => {
    return () => {
      resetCaptureManager();
      resetStorageManager();
      resetApiClient();
    };
  }, []);

  const checkRateLimit = (): boolean => {
    const now = Date.now();
    const { requests, maxRequests, windowMs } = rateLimitRef.current;

    const validRequests = requests.filter(time => now - time < windowMs);
    rateLimitRef.current.requests = validRequests;

    if (validRequests.length >= maxRequests) {
      return false;
    }

    rateLimitRef.current.requests.push(now);
    return true;
  };

  const openReporter = (options: { category?: string; prefill?: Record<string, any> } = {}) => {
    setReporterOptions(options);
    setIsModalOpen(true);
  };

  const closeReporter = () => {
    setIsModalOpen(false);
    setReporterOptions({});
  };

  const submitIssue = async (formData: any): Promise<DiagnosticResponse | null> => {
    if (!checkRateLimit()) {
      const error = new Error('Rate limit exceeded. Please try again later.');
      onError?.(error);
      throw error;
    }

    setIsSubmitting(true);

    try {
      const captureManager = captureManagerRef.current;
      const apiClient = apiClientRef.current;

      // Remove attachments from formData - they should NOT be sent as base64
      // Attachments should be uploaded separately using signed URLs
      const { attachments, ...formFields } = formData;

      const payload = {
        publishableKey,
        user,
        meta: captureManager.getCaptureMeta(),
        console: capture.console !== false ? captureManager.getConsoleLogs() : undefined,
        network: capture.networkSample ? captureManager.getNetworkLogs() : undefined,
        form: formFields,
        // DO NOT include attachments in JSON payload - use signed URL upload instead
      };

      const { issueId } = await apiClient.submitIssue(payload);

      onAfterSubmit?.(issueId);

      // Return the issue ID so uploads can be attached
      return { issueId, status: 'pending' as const, diagnostic: undefined };
    } catch (error) {
      const err = error instanceof Error ? error : new Error('Failed to submit issue');
      onError?.(err);
      throw err;
    } finally {
      setIsSubmitting(false);
      // Don't close reporter here - let the modal handle it after uploads
    }
  };

  const clearDiagnostic = () => {
    setLastDiagnostic(null);
    if (lastDiagnostic?.issueId) {
      storageManagerRef.current.markDiagnosticAsViewed(lastDiagnostic.issueId);
    }
  };

  const config: BlarioConfig = useMemo(
    () => ({
      publishableKey,
      apiBaseUrl,
      user,
      locale,
      capture: {
        console: capture.console ?? true,
        networkSample: capture.networkSample ?? false,
        maxConsoleLogs: capture.maxConsoleLogs ?? 50,
        maxNetworkLogs: capture.maxNetworkLogs ?? 20,
      },
      theme: {
        mode: theme.mode ?? 'light',
        position: theme.position ?? 'bottom-right',
        accent: theme.accent,
        className: theme.className,
      },
      redaction,
      rateLimit: {
        maxRequests: rateLimit.maxRequests ?? 10,
        windowMs: rateLimit.windowMs ?? 60000,
      },
      onAfterSubmit,
      onError,
    }),
    [
      publishableKey,
      apiBaseUrl,
      user,
      locale,
      capture,
      theme,
      redaction,
      rateLimit,
      onAfterSubmit,
      onError,
    ]
  );

  const value: BlarioContextValue = {
    config,
    isModalOpen,
    openReporter,
    closeReporter,
    reporterOptions,
    lastDiagnostic,
    isSubmitting,
    submitIssue,
    clearDiagnostic,
    user,
    locale,
  };

  return (
    <BlarioContext.Provider value={value}>
      <div className={cn("blario-wrapper", theme.mode === "dark" && "dark", theme.className)}>
        {children}
        <IssueReporterModal />
      </div>
    </BlarioContext.Provider>
  );
}

export function useBlarioContext(): BlarioContextValue {
  const context = useContext(BlarioContext);
  if (!context) {
    throw new Error('useBlarioContext must be used within a BlarioProvider');
  }
  return context;
}
